# Generated by Django 2.1.4 on 2019-02-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('roll_no', models.CharField(max_length=10)),
                ('std', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
    ]
